project: Recommending
datamodule:
  directory: local/ml-100k
  train_explicit_file: u1.base
  val_explicit_file: u1.test
  test_explicit_file: u1.test
logger:
  class_name: WandbLogger
  save_dir: local
callbacks:
  RecommendingIMDBCallback:
    path_to_imdb_ratings_csv: local/my_imdb_ratings.csv
    path_to_movielens_folder: local/ml-100k
    n_recommendations: 10
  RecommendingMetricsCallback:
    k: 10
