entity: dkoshman
project: Recommending
data:
  - artifact: dkoshman/Recommending/imdb_ratings:latest
    directory: data/imdb_ratings
    create_artifact_if_doesnt_exist: True
datamodule:
  movielens:
    class_name: MovieLens100k
    directory: local/ml-100k
  train_explicit_file: u1.base
  val_explicit_file: u1.test
  test_explicit_file: u1.test
loss:
  class_name: MSELoss
optimizer:
  class_name: Adam
logger:
  class_name: WandbLogger
  save_dir: local
#profiler:
#  class_name: WandbProfiler
trainer:
  default_root_dir: local
  amp_backend: native
#  amp_backend: apex
#  strategy: ddp
callbacks:
  WandbSaveCodeOnceCallback: {}
  LearningRateMonitor: {}
  ParameterStatsLoggerCallback: {}
  RecommendingMetricsCallback: {}
  RecommendingExplanationIMDBCallback:
    path_to_imdb_ratings_csv: data/imdb_ratings/my_imdb_ratings.csv
