name: "Implicit matrix factorization run"
model:
  class_name: ImplicitMatrixFactorizationRecommender
  implicit_model: BayesianPersonalizedRanking
  factors: 200
  learning_rate: 1.0e-2
  regularization: 1.0e-2
lightning_module:
  class_name: MovieLensNonGradientRecommender
trainer:
  num_sanity_val_steps: 0
callbacks:
  WandbWatcher:
    log_every_n_steps: 50
  WandbCheckpointCallback:
    artifact_name: implicit_als
