name: "My MF SLIM"
model:
  class_name: MFSlimRecommender
  latent_dimension: 100
  l2_regularization: 0.0
  l1_regularization: 1.0e-6
loss:
  class_name: MSELoss
datamodule:
  num_workers: 4
  batch_size: 1000
lightning_module:
  class_name: MovieLensMFRecommender
trainer:
  max_epochs: 1000
  accelerator: gpu
  devices: [5]
  check_val_every_n_epoch: 10
  log_every_n_steps: 1
callbacks:
  EarlyStopping:
    monitor: val_ndcg@10
    mode: max
    check_on_train_epoch_end: False
  WandbCheckpointCallback:
    monitor: val_ndcg@10
    mode: max
    save_on_train_epoch_end: False
    artifact_name: my_mf_slim

