name: "My MF"
model:
  class_name: MyMFConfidenceRecommender
  latent_dimension: 100
loss:
  ratings_deviation: 0.1
datamodule:
  num_workers: 4
  batch_size: 1000
lightning_module:
  class_name: MovieLensMFRecommender
optimizer:
  class_name: Adam
trainer:
  max_epochs: 1000
  accelerator: gpu
  devices: [2]
  default_root_dir: local
  amp_backend: native
  check_val_every_n_epoch: 10
  log_every_n_steps: 1
callbacks:
  ConvenientCheckpointLogCallback: {}
  EarlyStopping:
    monitor: val_loss
  WandbCheckpointCallback:
    artifact_name: my_mf
