name: "SVD run"
artifacts:
  - full_artifact_name: dkoshman/Recommending/imdb_ratings:latest
    directory: data/imdb_ratings
    match_directory_exactly: True
  - full_artifact_name: dkoshman/Recommending/movielens25m:v2
    directory: data/ml-25m
model:
  class_name: SVDRecommender
  n_components: 100
datamodule:
  movielens:
    class_name: MovieLens25m
    directory: data/ml-25m
  train_explicit_file: ratings_train.csv
  val_explicit_file: ratings_val.csv
  test_explicit_file: ratings_test.csv
  batch_size: 1000
lightning_module:
  class_name: MovieLensNonGradientRecommender
trainer:
  num_sanity_val_steps: 0
callbacks:
  WandbCheckpointCallback:
    save_on_train_epoch_end: False
    artifact_name: svd_movielens_25m
  RecommendingMetricsCallback:
    assess_online_recommendations: true
