project: Recommending
name: "SLIM"
method: random
metric:
  goal: maximize
  name: test_ndcg@10.mean
parameters:
  model:
    class_name: SLIM
    l2_coefficient:
      values:
        - 1.0e-6
        - 1.0e-5
        - 1.0e-4
    l1_coefficient:
      values:
        - 1.0e-5
        - 1.0e-4
        - 1.0e-3
        - 1.0e-2
        - 1.0e-1
  loss:
    class_name: MSEConfidenceLoss
    confidence:
      min: 0
      max: 1
  datamodule:
    num_workers: 4
  lightning_module:
    class_name: MovieLensSLIMRecommender
    patience: 3
    min_delta:
      values:
        - 1.0e-6
        - 1.0e-5
        - 1.0e-4
  optimizer:
    class_name: Adam
  trainer:
    accelerator: gpu
    devices: [4]
    reload_dataloaders_every_n_epochs: 1
    accumulate_grad_batches: 1
    enable_model_summary: false
    limit_val_batches: 0
    log_every_n_steps: 1
    default_root_dir: local
    num_sanity_val_steps: 0
    max_epochs: -1
